# Base de définitions BRVM extraite de DEFINITIONS-04_-DG.doc
# Chaque entrée : "TERME" : "définition complète"

DEFINITIONS_BRVM = {
    "BOURSE DES VALEURS": "Lieu où se rencontrent l'offre et la demande de valeurs mobilières.",
    "ACTION": "Valeur mobilière représentant une part de capital d'une société. C’est un titre de propriété.",
    "ACTIONNAIRE": "Détenteur d'une action est appelé un actionnaire.",
    "OBLIGATION": "Valeur mobilière représentant une part de dette d'une société, de l'Etat, ou d’une collectivité locale.",
    "DROITS": "Titre conférant à un actionnaire ordinaire le droit d’acheter d’autres actions à un prix fixé à l’avance.",
    "ORDRE D’ACHAT": "Décision (ou requête) d’un investisseur portant sur l’acquisition de valeurs mobilières.",
    "ORDRE DE VENTE": "Décision (ou requête) d’un investisseur portant sur la cession de valeurs mobilières.",
    "INDICE BOURSIER": "Indicateur  de la performance d’un marché boursier ou d’un panier de titres.",
    "BRVM 10": "Indice représentant la performance des dix valeurs les plus actives au cours  d’un trimestre à la BRVM",
    "BRVM composite": "Indice représentant la performance de l’ensemble du marché action de la BRVM",
    "SOCIETE DE GESTION ET D’INTERMEDIATION (SGI)": "Société agréée par le CREPMF et  habilitée à effectuer l’activité d’intermédiation financière sur la BRVM.",
    "ACTION ORDINAIRE": "Titre représentatif d’une participation ou d’une part de propriété dans une entreprise et qui donne un droit de vote lors des assemblées des actionnaires.",
    "ACTION PRIVILEGIEE": "Action d’une société accordant généralement à son détenteur le droit de recevoir un dividende fixe qui a une priorité sur les actions ordinaires de la société et une somme fixe en cas de liquidation.",
    "APPORTEUR D’AFFAIRES": "Personne physique ou morale, agréée par le CREPMF, qui met en relation un client avec une Société de Gestion et d’Intermédiation  ou une Société de Gestion de Patrimoine.",
    "ARBITRAGE": "Désigne généralement une opération suivant laquelle l’on tire profit d’une situation de déséquilibre sur le marché.",
    "AUGMENTATION DE CAPITAL": "Accroissement du capital d’une entreprise par émission d’actions nouvelles, incorporation des réserves ou distribution d’actions gratuites.",
    "BENEFICE NET": "Bénéfice d’une société après amortissements, provisions et impôts.",
    "BENEFICE PAR ACTION": "Bénéfice net rémunérant le détenteur d’une action. Il s’obtient en divisant le résultat net par le nombre d’actions composant le capital social.",
    "BON DE SOUSCRIPTION": "Valeur mobilière donnant le droit à son détenteur d’acheter un titre à un prix déterminé à l’avance  pour une échéance déterminée.",
    "CAPITALISATION BOURSIERE": "Valeur d’une société en bourse, obtenue en multipliant le cours de bourse par le nombre d’actions composant le capital social de la société.",
    "COTATION": "Opération par laquelle un titre financier est inscrit sur le marché boursier pour faire l’objet d’achat et de vente.",
    "COUPON": "Intérêt versé au détenteur d’une obligation.",
    "DIVIDENDE": "Part du bénéfice distribuée aux actionnaires au prorata des actions détenues.",
    "DROIT DE SOUSCRIPTION": "Droit négociable attaché à chaque action qui peut être utilisé ou cédé lors d’une émission d’actions contre espèces.",
    "INVESTISSEUR": "Personne physique ou morale qui place des capitaux dans la perspective d’une rentabilité.",
    "RENDEMENT EN DIVIDENDE": "Rapport entre le dividende et le cours de l’action.",
    "VOLUME DE TRANSACTIONS": "Nombre de titres échangés.",
    "LIQUIDITE DE MARCHE": "Capacité du marché à absorber rapidement les ordres d’achats et de ventes de titres sans écarts exagérés des cours des titres. Plus un marché est liquide, plus il est aisé, rapide et peu coûteux d'y réaliser des transactions.",
    "OPCVM (Organisme de Placement Collectif en Valeurs Mobilières)": "Organisme qui a pour objet la gestion collective de fonds investis en valeurs mobilières",
    "PER (Price Earning Ratio) – Ratio Cours/Bénéfice": "Rapport du cours en bourse sur le bénéfice par action. Il permet généralement d’apprécier la cherté d’une action.",
    "PLUS-VALUE": "Gain potentiel (plus-value latente) ou réalisé (plus-value réelle) sur le marché.",
    "MOINS-VALUE": "Perte potentielle (moins-value latente) ou réalisée (moins-value réelle) sur le marché.",
    "UN PORTEFEUILLE BOURSIER": "Ensemble de valeurs mobilières détenues par un investisseur.",
    "APPEL PUBLIC A L’EPARGNE": "Opération par laquelle un émetteur ouvre la souscription à ses titres au grand public.",
    "CARNET D'ORDRES": "Registre où sont regroupés tous les ordres saisis en attente d'une négociation ou d'une cotation.",
    "COURS COTE": "Niveau de prix auquel se négocie une valeur sur une base unitaire.",
    "COURS D'OUVERTURE": "Premier cours coté par une valeur lors de l'ouverture de la séance.",
    "COURS DE CLÔTURE": "Dernier cours du titre  à la fermeture du marché.",
    "ÉVENEMENT SUR VALEUR": "Détachement d'un droit de souscription, d'un droit d'attribution, d'un coupon , d'un de dividende ou toute autre opération reconnue comme telle par une Instruction ou un Avis de la Bourse.",
    "SEANCE DE BOURSE": "Période pendant laquelle se déroule la négociation de valeurs mobilières sur un marché boursier.",
    "TRANSFERT DU DROIT DE PROPRIETE": "Changement de la propriété d’une valeur mobilière",
    "APPARIEMENT": "Opération consistant à réunir un ordre d'achat à un ordre de vente dont les prix sont compatibles de manière à créer une transaction.",
    "OFFRE PUBLIQUE D'ECHANGE (OPE)": "Procédure par laquelle une personne physique ou morale fait connaître publiquement qu'elle s'engage à acquérir une quantité de titres d'un émetteur en payant avec d'autres titres plutôt qu'en numéraire.",
    "OFFRE PUBLIQUE DE RETRAIT (OPR)": "Procédure d'offre publique d'achat qui vise les actionnaires minoritaires d'une société, avec l'objectif avoué de faire procéder par les actionnaires majoritaires à la radiation des titres de cet émetteur de la cote.",
    "OFFRE PUBLIQUE DE VENTE (OPV)": "Procédure par laquelle un (ou plusieurs) détenteur(s) de titres fait connaître publiquement son intention de céder une quantité déterminée de titres à un prix ferme et définitif.",
    "VALEUR MOBILIÈRE": "Titres émis par une entreprise et négociables sur un marché Financier.",
    "RENTABILITÉ": "Capacité d´un capital investi dans différents actifs à procurer des revenus.",
    "SOUSCRIPTION": "Achat d'actions ou d'obligations lors d'une émission.",
    "TAUX D'INTÉRÊT": "Rémunération annuelle exprimée en pourcentage.",
    "TAUX FIXE": "Taux déterminé dans le contrat d'émission et définitivement fixe.",
    "TAUX VARIABLE": "Taux négociable ou qui évolue selon l’évolution d’un sous-jacent ou d’un indice.",
    "TAUX LONG": "Taux en vigueur pour des emprunts d'une durée supérieure à cinq (5) ans.",
    "NIVEAU DE PRIX": "Quantité théorique établie en francs CFA et susceptible d'être retenue comme cours coté pour une valeur déterminée pendant une séance de bourse donnée.",
    "BON DU TRÉSOR": "Créance négociable émise par un Trésor Public et permettant le financement à court et moyen terme d’un État.",
    "DATE DE DÉTACHEMENT": "Jour du paiement de dividendes à l'actionnaire.",
    "FONDS COMMUN DE PLACEMENT (FCP)": "Portefeuille de valeurs mobilières en copropriété, géré par une société de gestion pour le compte des porteurs de parts.",
    "DATE DE JOUISSANCE": "Date à partir de laquelle une action donne droit au dividende (jouissance au 1er janvier).",
    "DATE DE VALEUR": "Date à laquelle prend effet l'inscription au compte d'une opération ou date de règlement/livraison sur une transaction.",
    "TITRE": "Représentation des actions, parts, obligations et autres titres de créance.",
    "VALEUR LIQUIDATIVE": "Valeur des actifs détenus en portefeuille et rapportés à chaque part dans les SICAV et les FCP et calculée à une fréquence déterminée.",
    "TITRISATION": "Technique financière consistant à transférer à des investisseurs un portefeuille de créances en émettant des titres représentatifs de cette dette.",
    "DURATION": "La duration d'un instrument financier à taux fixe, comme une obligation, est la durée de vie moyenne de ses flux financiers pondérée par leur valeur actualisée.",
    "PRIME DE RISQUE ACTIONS": "Retour sur investissement supplémentaire offert par une action par rapport à un investissement sans risque. Ce rendement supplémentaire rémunère l'investisseur pour sa plus grande prise de risque.",
}
